### ISSUE TITLE
Link-card Issue

### ISSUE THREAD

**Issue by zannallan** [zannallan/link-card#1]
I can't figure out how to make it so the dt and dd tags in in the descriptive list are side by side but still in block alignment to each other. Need some help for this one please! @thomasjbradley

**Comment by thomasjbradley** [comment]
Get rid of `float`—it’s your enemy in this situation.
`display: inline-block` will work okay—with a `width` of about `45%`

**Comment by zannallan** [comment]
> Get rid of `float`—it’s your enemy in this situation.
> `display: inline-block` will work okay—with a `width` of about `45%`

Thank you!
